config/routes.rb
Rails.application.routes.draw do
  root 'programming_languages#index'
  resources :programming_languages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/programming_language.rb
class ProgrammingLanguage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/programming_languages_controller.rb
class ProgrammingLanguagesController < ApplicationController
  before_action :set_programming_language, only: %i[ show edit update destroy ]

  # GET /programming_languages or /programming_languages.json
  def index
    @programming_languages = ProgrammingLanguage.all
  end

  # GET /programming_languages/1 or /programming_languages/1.json
  def show
  end

  # GET /programming_languages/new
  def new
    @programming_language = ProgrammingLanguage.new
  end

  # GET /programming_languages/1/edit
  def edit
  end

  # POST /programming_languages or /programming_languages.json
  def create
    @programming_language = ProgrammingLanguage.new(programming_language_params)

    respond_to do |format|
      if @programming_language.save
        format.html { redirect_to programming_language_url(@programming_language), notice: "Programming language was successfully created." }
        format.json { render :show, status: :created, location: @programming_language }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @programming_language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programming_languages/1 or /programming_languages/1.json
  def update
    respond_to do |format|
      if @programming_language.update(programming_language_params)
        format.html { redirect_to programming_language_url(@programming_language), notice: "Programming language was successfully updated." }
        format.json { render :show, status: :ok, location: @programming_language }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @programming_language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programming_languages/1 or /programming_languages/1.json
  def destroy
    @programming_language.destroy

    respond_to do |format|
      format.html { redirect_to programming_languages_url, notice: "Programming language was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_programming_language
      @programming_language = ProgrammingLanguage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def programming_language_params
      params.require(:programming_language).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/programming_languages_helper.rb
module ProgrammingLanguagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProgrammingLanguages</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/programming_languages/_form.html.erb
<%= form_with(model: programming_language) do |form| %>
  <% if programming_language.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(programming_language.errors.count, "error") %> prohibited this programming_language from being saved:</h2>

      <ul>
        <% programming_language.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/programming_languages/_programming_language.html.erb
<div class="programming_language">
  <h2><%= programming_language.name %></h2>
  <p><%= programming_language.description %></p>
  <p>
    <%= link_to 'Show', programming_language %> |
    <%= link_to 'Edit', edit_programming_language_path(programming_language) %> |
    <%= link_to 'Delete', programming_language, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
</div>

app/views/programming_languages/edit.html.erb
<h1>Editing programming language</h1>

<%= render "form", programming_language: @programming_language %>

<br>

<div>
  <%= link_to "Show this programming language", @programming_language %> |
  <%= link_to "Back to programming languages", programming_languages_path %>
</div>

app/views/programming_languages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Programming Languages</h1>

<div id="programming_languages">
  <% @programming_languages.each do |programming_language| %>
    <%= render partial: 'programming_language', locals: { programming_language: programming_language } %>
  <% end %>
</div>

<%= link_to 'New Programming Language', new_programming_language_path %>

app/views/programming_languages/new.html.erb
<h1>New programming language</h1>

<%= render "form", programming_language: @programming_language %>

<br>

<div>
  <%= link_to "Back to programming languages", programming_languages_path %>
</div>

app/views/programming_languages/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <h1><%= @programming_language.name %></h1>
  <p><%= @programming_language.description %></p>
</div>

<div>
  <%= link_to "Edit this programming language", edit_programming_language_path(@programming_language) %> |
  <%= link_to "Back to programming languages", programming_languages_path %>

  <%= button_to "Delete this programming language", @programming_language, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>